Resolve error:
  - Property 'gtag' does not exist on type 'Window & typeof globalThis'.
  - Fix based on https://robkendal.co.uk/blog/how-to-fix-property-does-not-exist-on-window-type-in-typescript